Adoptify-System-370-Final-/AdoptifySystem/AdoptifySystem/Models/Veterinarian.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AdoptifySystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Veterinarian
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Veterinarian()
    {

        this.Vet_Appointment = new HashSet<Vet_Appointment>();

    }


    public int Vet_ID { get; set; }

    public string Vet_Name { get; set; }

    public string Vet_Emial { get; set; }

    public string Vet_Tel { get; set; }

    public string Vet_Address { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vet_Appointment> Vet_Appointment { get; set; }

}

}

Adoptify-System-370-Final-/AdoptifySystem/AdoptifySystem/Controllers/VeterinariansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdoptifySystem;
using AdoptifySystem.Models;

namespace AdoptifySystem.Controllers
{
    public class VeterinariansController : Controller
    {
        private Wollies_ShelterEntities db = new Wollies_ShelterEntities();

        // GET: Veterinarians
        public ActionResult Index()
        {
            return View(db.Veterinarians.ToList());
        }

        // GET: Veterinarians/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veterinarian veterinarian = db.Veterinarians.Find(id);
            if (veterinarian == null)
            {
                return HttpNotFound();
            }
            return View(veterinarian);
        }

        // GET: Veterinarians/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Veterinarians/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Vet_ID,Vet_Name,Vet_Emial,Vet_Tel,Vet_Address")] Veterinarian veterinarian)
        {
            if (ModelState.IsValid)
            {
                db.Veterinarians.Add(veterinarian);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(veterinarian);
        }

        // GET: Veterinarians/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veterinarian veterinarian = db.Veterinarians.Find(id);
            if (veterinarian == null)
            {
                return HttpNotFound();
            }
            return View(veterinarian);
        }

        // POST: Veterinarians/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Vet_ID,Vet_Name,Vet_Emial,Vet_Tel,Vet_Address")] Veterinarian veterinarian)
        {
            if (ModelState.IsValid)
            {
                db.Entry(veterinarian).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(veterinarian);
        }

        // GET: Veterinarians/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veterinarian veterinarian = db.Veterinarians.Find(id);
            if (veterinarian == null)
            {
                return HttpNotFound();
            }
            return View(veterinarian);
        }

        // POST: Veterinarians/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)


        {
            Veterinarian veterinarian = db.Veterinarians.Find(id);
            db.Veterinarians.Remove(veterinarian);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search(string searchBy, string search)
        {
            if (searchBy == "Vet_Name")
            {
                return View(db.Veterinarians.Where(c => c.Vet_Name.Contains(search) || search == null).ToList());
            }
            else
            {
                return View(db.Veterinarians.Where(c => c.Vet_Address.Contains(search) || search == null).ToList());
            }

        }
    }
}

Adoptify-System-370-Final-/AdoptifySystem/AdoptifySystem/Views/Veterinarians/Create.cshtml
@model AdoptifySystem.Veterinarian

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main">
    <div class="" style="text-align:center;padding-left:120px">
        <h3>Create New Veterinarian</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="panel panel-default" style="width:1200px">
            <div class="panel-heading">
                <h3 class="panel-title">Veterinarian Details</h3>
            </div>

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="row">
                    <div class="col-md-10">
                        <h4><span style="font-weight:bold">Name:<span class="label label-default"></span></span></h4>
                        @Html.EditorFor(model => model.Vet_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Vet_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
        
                        
                        
                        
                        
                        
                                        <h4><span style="font-weight:bold">Email:<span class="label label-default"></span></span></h4>
                        @Html.EditorFor(model => model.Vet_Emial, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Vet_Emial, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <h4><span style="font-weight:bold">Tel:<span class="label label-default"></span></span></h4>
                        @Html.EditorFor(model => model.Vet_Tel, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Vet_Tel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <h4><span style="font-weight:bold">Work Address:<span class="label label-default"></span></span></h4>
                        @Html.EditorFor(model => model.Vet_Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Vet_Address, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>
        </div>
   


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success glyphicon glyphicon-floppy-disk" />
        </div>

        <div class="form-group">
            <i class="glyphicon glyphicon-arrow-left">@Html.ActionLink("Back to List", "Index")</i>

        </div>
    </div>
    }
</div>

Adoptify-System-370-Final-/AdoptifySystem/AdoptifySystem/Views/Veterinarians/Delete.cshtml
@model AdoptifySystem.Veterinarian

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main">
    <div class="" style="text-align:center;padding-left:120px">
        <h1>Delete Veterinarian Details</h1>
    </div>

    <div class="panel panel-default" style="width:1200px">
        <div class="panel-heading">
            <h3 class="panel-title">Veterinarian Details</h3>
        </div>

        <h3 style="text-align:center">Are you sure you want to delete this Veterinarian Details?</h3>
        <div>

            <hr />
            <dl class="dl-horizontal" style="text-align:center">
                <dt>
                    Name:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Vet_Name)
                </dd>

                <dt>
                    Email:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Vet_Emial)
                </dd>

                <dt>
                    Tel:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Vet_Tel)
                </dd>

                <dt>
                    Address:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Vet_Address)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    @Html.ActionLink("Back to List", "Index", "Veterinarians", null, new { @class = "btn btn-primary glyphicon glyphicon-circle-arrow-left" })


                <input type="submit" value="Delete" class="btn btn-danger glyphicon glyphicon-trash pull-right" />

            </div>
            }
        </div>
    </div>
</div>

Adoptify-System-370-Final-/AdoptifySystem/AdoptifySystem/Views/Veterinarians/Details.cshtml
@model AdoptifySystem.Veterinarian

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="" style="text-align:center;padding-left:120px">
    <h1>Veterinarian</h1>
</div>

<div class="panel panel-default" style="width:1200px">
    <div class="panel-heading">
        <h3 class="panel-title">Veterinarian Details</h3>
    </div>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Name
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vet_Name)
            </dd>

            <dt>
                Email
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vet_Emial)
            </dd>

            <dt>
                Tel
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vet_Tel)
            </dd>

            <dt>
                Address
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vet_Address)
            </dd>

        </dl>
    </div>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Vet_ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

Adoptify-System-370-Final-/AdoptifySystem/AdoptifySystem/Views/Veterinarians/Edit.cshtml
@model AdoptifySystem.Veterinarian

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Veterinarian</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Vet_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Vet_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vet_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vet_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vet_Emial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vet_Emial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vet_Emial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vet_Tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vet_Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vet_Tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vet_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vet_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vet_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Adoptify-System-370-Final-/AdoptifySystem/AdoptifySystem/Views/Veterinarians/Index.cshtml
@model IEnumerable<AdoptifySystem.Veterinarian>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main">
    <div class="" style="text-align:center;padding-left:120px">
        <h1>Veterinarian Information</h1>
    </div>

    <div class="newButton">
        @Html.ActionLink("Add", "Create", "Veterinarians", null, new { @class = "btn btn-success 	glyphicon glyphicon-plus" })
    </div>
    <p>
        @using (Html.BeginForm("Index", "Veterinarians", FormMethod.Get))
        {
            <b>Search by:</b>@Html.RadioButton("Searchby", "Vet_Name", true) <text>Vet Name</text>
            @Html.RadioButton("Searchby", "Vet_Address")<text> Vet Address</text><br />
            @Html.TextBox("search")<input type="submit" value="Search" ? />
        }
    </p>
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                Tel
            </th>
            <th>
                Address
            </th>
            <th>
                Action
            </th>
            <th>

            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Vet_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vet_Emial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vet_Tel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vet_Address)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", "Veterinarians", new { id = item.Vet_ID }, new { @class = "btn btn-warning glyphicon glyphicon-pencil" })
                        @Html.ActionLink("Details", "Details", "Veterinarians", new { id = item.Vet_ID }, new { @class = "btn btn-primary glyphicon glyphicon-eye-open" })
                        @Html.ActionLink("Delete", "Delete", "Veterinarians", new { id = item.Vet_ID }, new { @class = "btn btn-danger glyphicon glyphicon-trash" })*@
                    <button class="btn btn-info glyphicon glyphicon-info-sign" data-toggle="modal" data-target="#@Html.DisplayFor(modelItem => item.Vet_ID)"> More Info</button>
                </td>
            </tr>

            <div id="@Html.DisplayFor(modelItem => item.Vet_ID)" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="info_card">
                        <div class="card_inner">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h2>  @Html.DisplayFor(modelItem => item.Vet_Name) </h2>
                            <hr />
                        </div>
                        <div class="data">

                            <span class="value">Email:</span>  @Html.DisplayFor(modelItem => item.Vet_Emial) <br />

                            <span class="value">Tel:</span>@Html.DisplayFor(modelItem => item.Vet_Tel)<br />

                            <span class="value">Address:</span> @Html.DisplayFor(modelItem => item.Vet_Address)<br />
                            <br />
                            <div class="">
                                @Html.ActionLink("Edit", "Edit", "Veterinarians", new { id = item.Vet_ID }, new { @class = "btn btn-warning glyphicon glyphicon-pencil" })
                                @Html.ActionLink("Details", "Details", "Veterinarians", new { id = item.Vet_ID }, new { @class = "btn btn-info glyphicon glyphicon-eye-open" })
                                @Html.ActionLink("Delete", "Delete", "Veterinarians", new { id = item.Vet_ID }, new { @class = "btn btn-danger glyphicon glyphicon-trash" })
                            </div>
                            <br />
                            <button type="button" class="btn btn-primary glyphicon glyphicon-remove" data-dismiss="modal"><i></i>Close</button>
                        </div>
                    </div>

                </div>
            </div>
        }

    </table>
    @Html.ActionLink("Refresh", "Index", "Veterinarians", null, new { @class = "btn btn-primary 	glyphicon glyphicon-refresh" })
</div>